#include "lang.h"

char strings_arr[][2][201] = {
        {"学生信息管理系统","STUDENT MANAGER SYSTEM"},
        {"你好，现在需要做一些首次使用的配置。","Hello, let's do some configurations for first using."},
        {"请输入学校名称：","Please type the name of your school:"},
        {"已全部完成。感谢你的耐心等待...","All done. Thanks for your waiting..."},
        {"功能菜单","Functions Menu"},
        {"重置系统配置","Reset Config"},
        {"使用帮助","Help"},
        {"保存并退出","Save & Exit"},
        {"开始录入","Start Inputting"},
        {"浏览上一页","Back Page"},
        {"浏览下一页","Next Page"},
        {"姓名查询","Query with Name"},
        {"批量删除","Delete in Batch"},
        {"排序浏览","Browse in Sort"},
        {"未录入任何数据。使用 [开始录入] 命令添加学生信息。",
         "There is not any data. Add data by [Start Inputting] command."},
        {"男性","Male"},
        {"女性","Female"},
        {"其他","Other"},
        {"页","Page"},
        {"请输入命令代码或要编辑的学生学号：","Please input the code of command or School ID:"},
        {"准备开始录入数据。","Prepare for Data Inputting."},
        {"在这之前，请告诉我们从哪里开始录入。请输入一个已记录的学号，之后，我们将会从这条数据之后开始插入新数据。",
         "To start, please tell us where to insert new data. Type an existed School ID below, and we will insert new data at the bottom of that data."},
        {"输入“#”代表从数据表的头部开始插入新数据；输入“-”代表从数据表的最后开始插入新数据。",
         "Insert new data in the front of data table by typing \"#\", and in the bottom of data table by typing \"-\"."},
        {"输入的学号无效。","The School ID your typed is invalid."},
        {"你将在这条数据之后录入新的数据：","You will insert new data in the bottom of this data:"},
        {"学号：","School ID:"},
        {"姓名：","Name:"},
        {"性别（[0] 男性 | [1] 女性 | [2] 其他）：","Sex([0] Male | [1] Female | [2] Other):"},
        {"年龄：","Age:"},
        {"生日（格式为 yyyy.mm.dd）：","Birthday(Format yyyy.mm.dd):"},
        {"住址：","Address:"},
        {"电话号码：","TEL:"},
        {"电子邮箱地址：","E-Mail Address:"},
        {"成绩（0~100）：","Grade(0~100):"},
        {"输入格式有误，请重新输入。","Your typing format is invalid, please try it again."},
        {"请输入“Y”以继续。","Type \"Y\" to continue."},
        {"学号","School ID"},
        {"姓名","Name"},
        {"性别","Sex"},
        {"年龄","Age"},
        {"生日","Birthday"},
        {"成绩","Grade"},
        {"编辑数据","Edit Data"},
        {"删除此学生信息","Delete The Student Data"},
        {"请输入命令代码或要编辑的条目代码：","Please input the code of command or data to edit:"},
        {"是否删除此学生信息？输入“Y”以继续。","Do you want to delete this data? Type \"Y\" to continue."},
        {"请输入一个姓名以供我们查询：","Please input a name to query:"},
        {"无查询结果。","No results."},
        {"请输入目标学生数据的学号以删除：","Please input the School ID to delete:"},
        {"删除成功。","Delete successfully."},
        {"请选择一种排序方式：","Please choose a sort type:"},
        {"按学号排序","Sort by School IDs"},
        {"按成绩排序","Sort by Grades"},
        {"当前无任何数据。","No any data."},
        {"总计","Count"},
        {"数据概览","Data Viewer"}
};